<?php
/**
 * Professio_BudgetMailer extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * https://gitlab.com/budgetmailer/budgetmailer-mag1/blob/master/LICENSE
 * 
 * @category       Professio
 * @package        Professio_BudgetMailer
 * @copyright      Copyright (c) 2015 - 2017
 * @license        https://gitlab.com/budgetmailer/budgetmailer-mag1/blob/master/LICENSE
 */

/**
 * Subscription widget
 * 
 * @category   Professio
 * @package    Professio_BudgetMailer
 */

if (!$this->getConfigHelper()->isAdvancedFrontendEnabled()) {
    return '';
}

$style = $this->isSignupHidden() ? ' style="display: none"' : null;
$checked = $this->isSignupChecked() || $this->getFormData()->getBmIsSubscribed() ? ' checked="checked"' : null;
?>
<script type="text/javascript">
    var bm_li = '<li class="control"<?php print $style ?>>';
    bm_li += '<div class="input-box">';
    bm_li += '<input<?php print $checked ?> type="checkbox" name="bm_is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="bm_is_subscribed" class="checkbox" />';
    bm_li += '</div>';
    bm_li += '<label for="bm_is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>';
    bm_li += '</li>';

    var bm_list = $$('#form-validate .form-list')[0];
    
    $(bm_list).insert(bm_li);
</script>
