<?php
/**
 * Professio_BudgetMailer extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Professio
 * @package        Professio_BudgetMailer
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */

/**
 * Subscription widget
 * 
 * @category   Professio
 * @package    Professio_BudgetMailer
 */
?>
<script type="text/javascript">
    var bm_li = '<li class="control">';
    bm_li += '<div class="input-box">';
    bm_li += '<input type="checkbox" name="bm_is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="bm_is_subscribed"<?php if($this->getFormData()->getBmIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />';
    bm_li += '</div>';
    bm_li += '<label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>';
    bm_li += '</li>';
// XXX add dynamically subscribe button here... 
//#form-validate .form-list ... append li.control etc

    var bm_list = $$('#form-validate .form-list')[0];
    
    $(bm_list).insert(bm_li);
</script>